// Builds video/src/ads/registry.gen.ts from the ad components on disk. Subagents
// write ads/<slug>.tsx in parallel and never touch a shared index; the
// orchestrator regenerates this file before every render.

const ES_AD = /export\s+(?:const|function)\s+Ad\b/;

/** @param {Record<string, string>} archivos file name -> source, for the ads/ folder */
export function registrySource(archivos) {
  const anuncios = Object.keys(archivos)
    .filter((f) => f.endsWith('.tsx'))
    .sort();

  for (const f of anuncios) {
    if (!ES_AD.test(archivos[f])) throw new Error(`${f} must export an \`Ad\` component (export const Ad: AdComponent = ...)`);
  }

  const imports = anuncios.map((f, i) => `import { Ad as ad${i} } from './${f.replace(/\.tsx$/, '')}';`);
  const entradas = anuncios.map((f, i) => `  '${f.replace(/\.tsx$/, '')}': ad${i},`);
  return [
    '// GENERATED by scripts/gen-registry.mjs. Do not edit: it is rewritten before every render.',
    "import type { AdComponent } from '../types';",
    ...imports,
    '',
    'export const ads: Record<string, AdComponent> = {',
    ...entradas,
    '};',
    '',
  ].join('\n');
}
