// GENERATED by scripts/gen-registry.mjs. Do not edit: it is rewritten before every render.
import type { AdComponent } from '../types';
import { Ad as ad0 } from './charla-familias';
import { Ad as ad1 } from './ejemplo-destacado';
import { Ad as ad2 } from './ejemplo-estandar';
import { Ad as ad3 } from './ejemplo-virtual';
import { Ad as ad4 } from './oracion-virtual';
import { Ad as ad5 } from './refam-juvenil';

export const ads: Record<string, AdComponent> = {
  'charla-familias': ad0,
  'ejemplo-destacado': ad1,
  'ejemplo-estandar': ad2,
  'ejemplo-virtual': ad3,
  'oracion-virtual': ad4,
  'refam-juvenil': ad5,
};
